#!/bin/bash

# Logging Setup 
LOGFILE="./pg_db_creation.log"
echo "=== PostgreSQL Database Creation Log ===" >> "$LOGFILE"
echo "Started at $(date)" >> "$LOGFILE"

# User Input
read -p "Enter PostgreSQL username: " PGUSER

read -p "Enter the new user's username: " DB_USER
read -sp "Enter password for $DB_USER: " DB_PASS
echo
read -p "Enter the name of the database to create: " DBNAME


echo "Database '$DBNAME': Proceeding to create" | tee -a "$LOGFILE"


echo "put in $PGUSER password"
sudo psql -U $PGUSER -d postgres -W <<EOF

CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';
CREATE DATABASE $DBNAME;

-- conencting to database
/c $DBNAME;

-- grant privilages
GRANT CONNECT, USAGE ON DATABASE $DBNAME TO $DB_USER;
GRANT SELECT, INSERT, DELETE, UPDATE ON ALL TABLES IN SCHEMA public TO $DB_USER;
EOF

